services:
  minio:
    image: quay.io/minio/minio
    container_name: minio_local
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio-secret-key
      MINIO_VOLUMES: "/data"
      MINIO_OPTS: "--console-address :9001"
    command: server --console-address ":9001" /data

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - minio

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend



# docker compose up --build
# docker compose down --volumes